apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
  storageClassName: {{ .Values.pvcStorageClass }}
  volumeMode: Block
