apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed   
    argocd.argoproj.io/sync-wave: '0'
  name: {{ printf "%s-pvc" .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
  storageClassName: {{ .Values.pvcStorageClass }}
  volumeMode: Filesystem
